site_name: Config Finder
repo_url: https://github.com/fabfabi/simpleconfigfinder

theme:
  name: readthedocs
  hljs_languages:
    - python
    - toml
    - json
    - yaml
  features:
    - search.suggest
    - search.highlight
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.highlight # creates the ```python blocks
  #- pymdownx.superfences
  - pymdownx.snippets

plugins:
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        paths: [src]  # search packages in the src folder
        options:
          show_submodules: true
          separate_signature: true #converts function names to titles
          docstring_style: google
    watch:
      - src/simpleconfigfinder
- search

nav:
  - Start: 'index.md'
  - Code: 'configfinder.md'